"""generate model

Revision ID: 6db7b4a9b000
Revises: 
Create Date: 2022-03-23 15:26:08.455022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db7b4a9b000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    op.add_column('order', sa.Column('product_id', sa.String(), nullable=True))
    op.drop_column('order', 'provider_id')
    op.drop_column('order', 'package_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('package_id', sa.VARCHAR(), nullable=True))
    op.add_column('order', sa.Column('provider_id', sa.VARCHAR(), nullable=True))
    op.drop_column('order', 'product_id')
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider_id', sa.VARCHAR(), nullable=True),
    sa.Column('package_id', sa.VARCHAR(), nullable=True),
    sa.Column('order_time', sa.DATETIME(), nullable=True),
    sa.Column('delivery_time', sa.DATETIME(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
